export const NOTIFICATION_BAR_ERROR = 'ERROR';
export const NOTIFICATION_BAR_WARNING = 'WARNING';
export const NOTIFICATION_BAR_INFO = 'INFO';
export const NOTIFICATION_BAR_SUCCESSFULL = 'SUCCESS';
export const NOTIFICATION_BAR_NONE = 'NONE';
